name: Deploy Azure Function - Notificacao

on:
  push:
    branches: 
      - master  # Mude de main para master aqui
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Adicionamos permiss√µes para garantir que o GitHub consiga se comunicar com a Azure
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build
        run: mvn clean package -DskipTests

      - name: Deploy (Publish Profile)
        uses: Azure/functions-action@v1
        with:
          app-name: func-notificacao
          package: ./target/azure-functions/func-notificacao
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}